### ISSUE TITLE
[bug] SizeLimitExceededException

### ISSUE THREAD

**Issue by plinio** [MatchDog/grails#16]
Casos onde ocorre o erro:
Ao adicionar um segundo Dog para o mesmo usuário;
Ao adicionar mais de uma foto nos álbuns (de dog e de dono);

**Comment by arturcalves** [comment]
Não consegui reproduzir esse bug nas situações relatadas.
Apenas percebo esse erro quando no cadastro( ou edição) do dono, ou do dog, coloco uma foto com mais de 160Kb

**Comment by arturcalves** [comment]
Alterado a configuracao de tamanho de arquivos.
Mas, dependendo do servidor web, pode haver uma outra configuração, mas nomalmente essas não são tão pequenas.
